
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jacobs Development (https://sketchfab.com/Jacobs_Development)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-planet-earth-7b1dc4f802a54a6297e7a46888a85f77
title: Low Poly Planet Earth
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "react-three-fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/planet.glb");

   const myMesh = React.useRef();

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();
    myMesh.current.rotation.set(0.1 + Math.cos(a / 4.5) / 10, Math.sin(a / 4) / 4, 0.3 - (1 + Math.sin(a / 4)) / 8)
    myMesh.current.rotation.x = (1 + Math.sin(a / 2)) / 10;
    myMesh.current.rotation.y = a * 0.1

  });

  return (
    <group {...props} dispose={null}  ref={myMesh}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_Planet_0.geometry}
              material={materials.Planet}    
            />
    </group>
  );
}

useGLTF.preload("/planet.glb");


